services:
  crop-management:
    build:
      context: .
      dockerfile: Dockerfile
    image: crop-management:latest
    ports:
      - "8000:8000"
    env_file: app/.env
    volumes:
      - ./app:/app
