name: Deploy to EC2

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/IoT/suscriber/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{github.env.HOST_IP}}
          username: ${{ github.env.HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './src/IoT/suscriber/*'
          target: '/home/${{github.env.HOST_USER}}/my-app'

      - name: Execute deployment script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{github.env.HOST_IP}}
          username: ${{ github.env.HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/my-app
            pip install -r requirements.txt
            python main.py
